services:
  client:
    container_name: ipl-client
    image: node:22-alpine
    ports:
      - "3000:5173"
    volumes:
      - ./client:/app
    working_dir: /app
    build: ./client
    tty: true
    stdin_open: true
  
  server:
    container_name: ipl-server
    image: python:latest
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    tty: true
    working_dir: /app
    stdin_open: true
    build: ./server